name: CI PS4

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-ps4:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add ncurses-dev make bash python2 libstdc++

    - name: Get Information Variables
      id: core
      run: |
        echo "info=$(echo test)" >> $GITHUB_OUTPUT
        echo "platform=$(echo orbis)" >> $GITHUB_OUTPUT
        echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Compile test core
      run: |
        cd tests/test && make platform=${{ steps.core.outputs.platform }} clean all

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.core.outputs.info }}_libretro_${{ steps.core.outputs.platform }}-${{ steps.core.outputs.sha8 }}
        path: tests/test/${{ steps.core.outputs.info }}_libretro_${{ steps.core.outputs.platform }}.a
